### PR TITLE
Add demo and improve build process

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Comment by cmckni3** [comment]
Just need to test out the build process itself and try it in an application.

**Comment by cmckni3** [comment]
What do you think @webcat12345?

**Comment by webcat12345** [comment]
Just finished merge. and here is deployed url.
https://webcat12345.github.io/ngx-ui-switch/

I expected demo page, but this is just doc, isn't it?

**Comment by cmckni3** [comment]
Not sure where that came from. https://webcat12345.github.io/ngx-ui-switch/demo/ is working as the demo though.

**Comment by cmckni3** [comment]
I guess GHPages defaults to showing README.md as HTML.

**Comment by webcat12345** [comment]
Anway looks great. Thanks for your contributing!

**Comment by cmckni3** [comment]
No problem

Have you looked at getting it built and up to npm?

**Comment by webcat12345** [comment]
Yes, its build process fine.

**Comment by webcat12345** [comment]
https://github.com/webcat12345/ngx-ui-switch/invitations

Just invited you as a collaborator

**Comment by cmckni3** [comment]
Joined. Thanks!

**Comment by webcat12345** [comment]
Do you have npm account? I would like to add you owner of ngx-ui-switch, so you can have full access.

**Comment by cmckni3** [comment]
yup

https://www.npmjs.com/~cmckni3

**Comment by webcat12345** [comment]
Done, you can now update package version as well. Thank you for your passionate!

**Pull request merged**
