### PR TITLE
Added the ability to add content to the switch so its customizable.

### PR DESCRIPTION
**Pull request by mbejda**
Added the ability to add content to the switch so its customizable.

You can add

- web fonts
- images
- animations
- custom html

This closes feature request #311 and doesn't introduce any breaking changes.

### CODE REVIEW

**Comment by cmckni3** [comment]
Will cut a new release tomorrow.

Thanks!

**Comment by mbejda** [comment]
**I'm so happy :) 
<**img width="170" alt="screen shot 2019-01-20 at 5 10 15 am" src="https://user-images.githubusercontent.com/5429780/51437847-bb411e80-1c71-11e9-886c-b0ec04a4aa91.png">

**Comment by cmckni3** [comment]
haven't had a chance to create a release yet. Maybe some time today.

**Comment by cmckni3** [comment]
Published 8.0.0

**Comment by borisBelloc** [comment]
> **I'm so happy :)**
> 
> screen shot 2019-01-20 at 5 10 15 am

sorry, but how do you do that?
I didn't find any info on the doc about adding an image to the switch :(

**Pull request merged**
